export const API_SITE = 'http://localhost:8081'
export const LOGIN = '/api/login'
export const GET_ALL_PASSWORD = '/api/getAllPasswords'
export const CREATE_NEW_PASSWORD = '/api/createNewPassword'
export const EDIT_PASSWORD = '/api/editPassword'
export const DELETE_PASSWORD = '/api/deletePassword'
export const CREATE_NEW_ACCOUNT = '/api/createNewUser'
export const EDIT_ACCOUNT = '/api/editUser'